### PR TITLE
Reworked the way the sheet thickness is computed.

### PR DESCRIPTION
**Pull request by chappatted**
I had a few parts that I could not unfold because the script could not compute the sheet thickness correctly. Thus, I propose a different way to compute it. The attached part can't be unfolded with current method, but can be with the proposed one.

[22301_OK.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/9886264/22301_OK.zip)

### CODE REVIEW

**Comment by shaise** [comment]
Hi, 
I did not have any issues unfolding this file. can you explain the unfolding sequence that made it not to work?

**Comment by chappatted** [comment]
Hello,

What I did is:

1) Open FreeCAD 0.21
2) Open part
3) Switch to Sheet Metal
4) Select the largest face
5) Click the unfold button
6) Confirm in the unfold dialog with manual k-factor

Here is the error log:

> 16:42:28  Engineering mode is not enabled.
16:42:29  Manual K-factor is being used: 0.34 (ansi)
16:42:29  exception at line 2865("'NoneType' object has no attribute 'c_face_idx'",)
16:42:29  ("'NoneType' object has no attribute 'c_face_idx'",)
16:42:29  Traceback (most recent call last):
16:42:29    File "C:\Users\dch\AppData\Roaming\FreeCAD\Mod\sheetmetal\.\SheetMetalUnfolder.py", line 2865, in accept
    s, foldComp, norm, thename, err_cd, fSel, obN  = getUnfold(k_factor_lookup)
16:42:29    File "C:\Users\dch\AppData\Roaming\FreeCAD\Mod\sheetmetal\.\SheetMetalUnfolder.py", line 2173, in getUnfold
    TheTree.Bend_analysis(f_number, None) # traverses the shape and builds the tree-structure
16:42:29    File "C:\Users\dch\AppData\Roaming\FreeCAD\Mod\sheetmetal\.\SheetMetalUnfolder.py", line 1338, in Bend_analysis
    FreeCAD.Console.PrintLog("counterface on otherSeamNode: Face" + str(otherSeamNode.c_face_idx+1) + "\n")
16:42:29  AttributeError: 'NoneType' object has no attribute 'c_face_idx'
16:42:29  Engineering mode is not enabled.

**Comment by shaise** [comment]
Strange, on 0.21 for me it works without issues. Can you please open "Help -> about freecad" press the "copy to clipboard" and paste it here?

**Comment by chappatted** [comment]
I did not have the latest version of FreeCAD (I had an older nightly build) so I reinstalled it with latest SheetMetal version and this time it works.

However I have another part that I'm working on with the same problem : [Lucarne.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/9899066/Lucarne.zip) . It works if I select the bottm face, but it doesn't work if I select the top face because the chosen point is in a wrong place. However it works with this new method to compute sheet thickness.

Please note that the unfold result is wrong anyway, but I'm trying to fix that now.

**Comment by shaise** [comment]
The Lucarne shape can not be handled with the current unfolder as it only supports simple bends, not embossed patterns.

**Comment by chappatted** [comment]
> The Lucarne shape can not be handled with the current unfolder as it only supports simple bends, not embossed patterns.

Yes, I was looking at the macro to see if I could implement it but it doesn't seem trivial. Did you ever think about how it could be done?

**Comment by shaise** [comment]
The unfold macro was not done by me, and is quite complicated for me to dig into. So no, I have not thought to fix it.

**Comment by chappatted** [comment]
Closing this, will make new PR where new thickness computation is needed.

**Pull request closed without merging**
