### PR TITLE
Bug fix.

### PR DESCRIPTION
**Pull request by jaisekjames**
Revised all code. Now bend will work on all bend angles
Need testing.

### CODE REVIEW

**Comment by shaise** [comment]
this a very big code change, what was the bug? Does it affect loading of old files?

**Comment by ceremcem** [comment]
Plus, "Need testing" part made me anxious.

**Comment by jaisekjames** [comment]
Earlier version was based on fillet to create bend. Now it is based exactly same theory as unfolder macro. 
I am able generate bend solid wire. see link macro
[https://forum.freecadweb.org/viewtopic.php?f=22&t=47588#p412121](url)

But there is no way to create cylindrical faces from wire.  So I was used a work around by guessing top & bottom faces are same & cutcylinder face from it.

If we able to generate faces from wrapped wires, we can create any shapes with this code.

There is some function in OCC "BRepBuilderAPI_MakeFace cylface(cylinder_face, wire) - limit cylinder by wired edges". If some developer able look into it & if useful, exposed to python, we can generate any bend shape from our code.

**Comment by jaisekjames** [comment]
You can check folding using attached file in 

[https://forum.freecadweb.org/viewtopic.php?f=22&t=47588#p412121](url)

**Comment by shaise** [comment]
Did you try loading old files to check if the changes did not break anything?

**Comment by jaisekjames** [comment]
I checked for files, but there is no old file saved.

It will not break old since selection Procedure [face & sketch] is same. But there will be variation in results & face number change issue can happen because cutting position changes. New result will be match with other cads results also.

One Issue is there, here we use Part.makeFilledFace.  Some rare cases, it will generate hill like shape instead of cylinder. It will appear as holes in bends. I will check any other function to do that better.

**Pull request closed without merging**
