### PR TITLE
Improved the unfolding script to handle counterbore holes

### PR DESCRIPTION
**Pull request by chappatted**
Parts with counterbore holes can't be unfolded because the sheet thickness is not constant. See this part for example : [counterbore.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/9950638/counterbore.zip)

Here is a proposition to fix it. When building the sheet tree, the counterbores are detected and saved into a list. When the faces are cloned to build the new unfolded shape, the counterbores are replaced with regular holes. The diameter of the new hole is the smaller radius of the counterbore, since this is what matters in the sketch for laser cutting.

### CODE REVIEW

**Comment by luzpaz** [comment]
An aside, it be great to have some unittests that we can test new PRs like this against

**Comment by shaise** [comment]
your example does not unfold with your new code:
```
16:25:29  exception at line 3068("'SheetTree' object has no attribute 'face_normal'",)
16:25:29  ("'SheetTree' object has no attribute 'face_normal'",)
16:25:29  Traceback (most recent call last):
16:25:29    File "C:\Users\shai\AppData\Roaming\FreeCAD\Mod\FreeCAD_SheetMetalcb\.\SheetMetalUnfolder.py", line 3068, in accept
    s, foldComp, norm, thename, err_cd, fSel, obN  = getUnfold(k_factor_lookup)
16:25:29    File "C:\Users\shai\AppData\Roaming\FreeCAD\Mod\FreeCAD_SheetMetalcb\.\SheetMetalUnfolder.py", line 2376, in getUnfold
    TheTree.Bend_analysis(f_number, None) # traverses the shape and builds the tree-structure
16:25:29    File "C:\Users\shai\AppData\Roaming\FreeCAD\Mod\FreeCAD_SheetMetalcb\.\SheetMetalUnfolder.py", line 1357, in Bend_analysis
    if not self.handle_hole(parent_node, face_idx, edge, child_face, child_index):
16:25:29    File "C:\Users\shai\AppData\Roaming\FreeCAD\Mod\FreeCAD_SheetMetalcb\.\SheetMetalUnfolder.py", line 1421, in handle_hole
    dot = self.face_normal(next_faces[0])[0].dot(self.face_normal(parent_face)[0])
16:25:29  AttributeError: 'SheetTree' object has no attribute 'face_normal'
16:25:29  
```
I use freecad 20 release version

**Comment by chappatted** [comment]
Sorry, a method was missing. I added it, it should be working now.

**Comment by shaise** [comment]
Hi, tested, Works!
Usually, this type of part is considered "non legal" sheet metal part, but as long as it works correctly on "legal" parts I'm all for making the unfolder as forgiving as possible. (for example, it would be nice if the unfolder can support countersunk holes as well as counter bore)
So thanks!!!

**Comment by chappatted** [comment]
> Hi, tested, Works! Usually, this type of part is considered "non legal" sheet metal part, but as long as it works correctly on "legal" parts I'm all for making the unfolder as forgiving as possible. (for example, it would be nice if the unfolder can support countersunk holes as well as counter bore) So thanks!!!

Well it may not be "legal" because the sheet thickness is not constant, however having countersink/counterbore in a sheet metal is not necessarily a rarity. Next thing I would like to fix is unfolding parts with a chamfer, and we have the same problem there (thickness is non constant but this can happen in real world parts).

**Comment by shaise** [comment]
I completely agree. thanks!

**Pull request merged**
