### PR TITLE
K factor from lookup

### LINKED ISSUE #40: How to make unfold sketch updated on base geometry changes
This is the current unfold output: 

image

When I changed the geometry, for example as in the following way: 

image

I expect the unfold sketch to be updated accordingly. How can I achieve this, either automatically (this is preferred) or by manually running some code?

### LINKED ISSUE #68: Definition of k-factor
Internet searches as well as [Wikipedia page](https://en.wikipedia.org/wiki/Bending_(metalworking)#K-factor) shows that the definition of "k-factor" is as follows: 

> K-factor is a ratio of location of the neutral line to the material thickness as defined by t/T where t = location of the neutral line and T = material thickness. (...) and usually between 0.3 and 0.5. 

Based on this information, [latest change of k-factor in SheetMetal](https://github.com/shaise/FreeCAD_SheetMetal/commit/62c40b14fe6fea982b0b90c0490ea417b79cef51) is misleading, thus should be reverted.

Moreover, the formula [`newNode.k_Factor = (0.65 + 0.5*math.log10(innerRadius/self.__thickness))`](https://github.com/shaise/FreeCAD_SheetMetal/blob/bf2c0c1ecbda40ceedda646c1fdf63b39810c896/SheetMetalUnfolder.py#L828) has no explanation. It should be explained or removed. There is a long discussion about this formula in SW forum and seems that it's still unclear: https://forum.solidworks.com/thread/38306

### PR DESCRIPTION
**Pull request by ceremcem**
# Description 

This PR adds the "Material Definition Sheet" concept to SheetMetal. 

K-factor is now obtained:
* either from manual K-factor input (mandatory if you don't have a material definition sheet)
* or from a "Material Definition Sheet"

# Manual K-factor

Users are now required to click and enable the "Manual K-factor" checkbox each time they want to unfold. This approach makes us quite confident that the user is seriously warned about the "`kfactor`" property from any `Bend` operation is not being used, so user won't encounter an unexpected result because of a default K-factor:

k-factor-manual

# Using a Material Definition Sheet 

k-factor-lookup2

K-factor property of a Bend is **completely ignored** since K-factor has nothing to do with the geometric data. If it is required to use different K-factor values per bend, follow the below steps: 

1. Determine your material name (eg. `foo`)
2. Add `_material_foo` postfix to your shape 
3. Create a spreadsheet with the name of `material_foo`
4. Create a table layout in `material_foo`, like the following (see [this table](https://user-images.githubusercontent.com/6639874/56498031-b017bc00-6508-11e9-8b14-6076513d8488.png)): 

    | Radius / Thickness | K-factor | Options | | 
    | ---| ---| --- | --- |
    | 1 | 0.38 | K-factor standard | ANSI |
    | 3 | 0.43 | | |
    | 99 | 0.5 | | |

5. Unfold as usual

# Is Breaking?

No.

# Changelog 

* K-factor standard is required to be explicitly set. (closes #68, related to #54 )
* Terminology is added to the README (closes #68)
* Material definition sheet is required unless manual K-factor is being used (new feature). 
* Added "Update Unfold" macro which resolves #40
* Fixed some typo
* Cleanup console output

### CODE REVIEW

**Comment by shaise** [comment]
I like this approach much better!

However, I don't like the need to append the spreadsheet name to the bend.
This means that each time I add new feature to the model, I need to rename it.
I think it is better to create a spreadsheet with a known prefix, say "fold_material_xxx",
When you press unfold, it will take this spreadsheet automatically, and if there is more then
one, a drop down list will let me select.
If there is no spreadsheet, the manual K factor will be automatically selected. (in fact it can be
one of the options in the dropdown: Fold_material_xxx, fold_material_yyy, ...,  Manual.)

shai

**Comment by ceremcem** [comment]
> I like this approach much better!

Thanks. 

> This means that each time I add new feature to the model, I need to rename it.

It will be frustrating to rename the model each time, yes. However, it becomes unnecessary as your model *gets more complex* because, 

1. Let's assume that you created a Body and created some bends. You need to rename it to `Body_material_foo` for the first time, as normal. 
2. If you add more bends, you *don't need to rename* the model. 
3. If you apply a boolean operation, new name becomes, eg. Fusion; so you **need to rename** it. 
4. If you want to fuse more solids, just drop into the `Fusion` container, you *don't need to rename*.
5. If you create a Cut, you **need to rename**. 
6. If you create more cuts, just [replace the Cut tool with a Fusion of cut parts](https://forum.freecadweb.org/viewtopic.php?f=3&t=35689&p=301744#p301744), so you *don't need to rename*. 
7. After this point, you *won't need to rename anything anymore* as you can add any solid you want to cut with into `Cut.Tool.Fusion` and any solid you want to fuse with into `Cut.Base.Fusion`. 

Moreover, you would only rename the model one or two times because you would probably want to unfold accurately after your model is completed, so you would rename the resulting model only after your work is completely done. Before your work is completed, you can always test unfold by providing the manual K-factor.

It's quite possible to provide a dropdown to be used in manual operations. However, a problem I can think of is that providing a manual K-factor as well as a material definition sheet manually means the user is providing a crucial information manually, which means the project file depends on a serious information that only the user memorizes. Since a project won't be considered as "Completed" unless such a critical information can be stored within the project file, there *MUST* be a way to store that information. If we could store this information, then it becomes obsolete to provide such a manual selection interface.

**Comment by shaise** [comment]
Hi,

Sorry, but I really think that renaming an object as a way to add a
property into it is kind of a hack. It also very not intuitive to a user. A
user is doing good with selecting things and clicking buttons. Also, say
there is another workbench using the same technique, what then? rename the
object to Body_meterial_foo_otherproperty_bar ?

shai

**Comment by ceremcem** [comment]
> I really think that renaming an object as a way to add a
property into it is kind of a hack.

You are absolutely right. It's not a correct way to go considering the FreeCAD UX way, it's just a hack. 

It turns out that this kind of necessity might have lead us a new feature of FreeCAD: Propagated Properties (@realthunder would you comment on this?). A "Propagated Property" will be like any other property of the root object. If the object is encapsulated with some other operator (like Bend, Fuse, Cut, etc.) the property will be removed from its original location and added to the root object. Exploding a root operation (such as deleting a Cut) will result in moving the Propagated Properties (back again) to the newly created root object which was the `Base` object before explosion.

**Comment by ceremcem** [comment]
Latest commit adds the ANSI/DIN selection radio box, thus removes the "breaking" status of the PR: 

image

It's also required to declare `K-factor standard` explicitly in the `Options` within Material Definition Sheet: 

image

As the "Label renaming hack" is harmless and is only used to add a new feature, this PR is ready to be reviewed.

**Comment by shaise** [comment]
Having a selection of DIN/ANSI is a great Idea to settle this issue. 
I will review now the changes.

**Comment by shaise** [comment]
Hi ceremcem,

I took a look at it, and here is what I think:
First of all There is no problem to merge this change. The only lost feature is the automatically calculated K factor which I agree that in most cases there is no use for it.
The big concern however, is that your complicated changes which are great will be lost without use. When I try to unfold I get this message telling me to set a material definition sheet. That is great, but there is no way a user might guess how to do it. He will probably look hopelessly in the menu's to see where this "Material Sheet" is hiding.
There must be some kind of an online help connected to this message to explain how to do it. Or perhaps a button on the toolbar that generates a template sheet.

**Comment by ceremcem** [comment]
Do you think above instructions in the very first post of this PR is sufficient so I could add it to the README and point this document in the error message, or should it be more clear?

**Comment by shaise** [comment]
I think for a start its definitely good enough!

**Comment by ceremcem** [comment]
Added. Please see 7f14194

**Comment by ceremcem** [comment]
FYI: "Propagated Properties" issue has been risen in the FreeCAD forum: https://forum.freecadweb.org/viewtopic.php?f=3&t=35889

**Pull request merged**
