### PR TITLE
Overhaul sheet metal icons to be consistent with FreeCAD

### PR DESCRIPTION
**Pull request by maxwxyz**
PR with recreated icons to be consistent in the SheetMetal WB and across the FreeCAD application according to the [Artwork Guidelines](https://wiki.freecad.org/Artwork_Guidelines)
There are also some alternative versions included and some specific feature icons for the following DWG proposal.
@shaise just let me know if in need for further icons in the future.

Current icons:
grafik

New icons:
grafik

In FreeCAD:
grafik

Feedback is appreciated. 
If you don't like the green to indicate the feature/position it could be made all blue as well.

### CODE REVIEW

**Comment by shaise** [comment]
Hi @maxwxyz,
Wow! These icons are absolutely phenomenal.
Here are some changes I would like if it is OK with you:
for SheetMetal_AddBend, I prefer something like this:
image

For SheetMetal-AddRelief :
image

And for for SheetMetal-AddBaseShape I prefer upside down like this orientation:
image

All others are great, and also the first selection (non alt) is ok
Thanks!

**Comment by maxwxyz** [comment]
@shaise I'm on it.
Add bend: is this how its supposed to work? The backside gets no bend radius.
grafik

**Comment by maxwxyz** [comment]
@shaise done
grafik

**Comment by shaise** [comment]
Great! thanks!

**Comment by shaise** [comment]
Ah, and sorry, for your question about the bend:
image

when you manually set the correct width of the wall, this should have converted to a real bend, similar to the icon, however there seem to be a bug there, I need to take a look.

**Comment by shaise** [comment]
Hi @maxwxyz ,
OK. I have rewritten the entire bend function. It is now more robust, and it also detects the thickness automatically. Please update and try the example you tested to see if it is ok now.

**Comment by maxwxyz** [comment]
Nice

**Comment by shaise** [comment]
Thanks again for the icons. they are awesome.

**Comment by shaise** [comment]
Hi @maxwxyz ,

I'm working now on a new function that converts a solid to a sheetmetal object:
image
Can you please suggest an icon for it?

Thanks!!!!

**Comment by maxwxyz** [comment]
I'll take a look in the coming days

**Comment by maxwxyz** [comment]
@shaise what about this?
It is really hard to convey this at small icon size...
SheetMetal_ConvertSolid

**Comment by shaise** [comment]
Hi @maxwxyz 
Thanks!
Yes, this was exactly my problem. I was trying to do something along the line of SheetMetal_addJunction:
SheetMetal_FromSolid
but in small sizes it looks like a scribble.
I like yours better.

Can you zip and attach it again? I can not download it.

**Comment by maxwxyz** [comment]
@shaise 
[SheetMetal_ConvertSolid.zip](https://github.com/user-attachments/files/25865072/SheetMetal_ConvertSolid.zip)

**Comment by shaise** [comment]
Thanks!!

**Pull request merged**
