### PR TITLE
adding Unfold exception message + using 'is' to check 'None'

### PR DESCRIPTION
**Pull request by easyw**
referring to this thread
https://forum.freecadweb.org/viewtopic.php?f=22&t=25281&p=241335#p241312
I'm adding an exception message

### CODE REVIEW

**Comment by shaise** [comment]
thanks.

**Comment by shaise** [comment]
whats the difference between 'is' and '==' in this regard?

**Comment by easyw** [comment]
PEP 8 Style Guide
https://docs.quantifiedcode.com/python-anti-patterns/readability/comparison_to_none.html
https://stackoverflow.com/questions/3257919/what-is-the-difference-between-is-none-and-none

**Comment by shaise** [comment]
Thanks again!

**Pull request merged**
