### PR TITLE
Sheetmetal enchancement

### PR DESCRIPTION
**Pull request by jaisekjames**
* Added Edge based selection
* Added Auto-mitering
* Added Sketch based Wall
* Added Sketch based Guided wall
* Added Relief factor
* Added Material Inside, thk inside, Offset options

### CODE REVIEW

**Comment by shaise** [comment]
1. I saw in the freecad forum that there is an extra file: SheetMetalSketchCmd.py. Is it missing here?
2. when I try to make a simple bend (without the new features), I get an error:
Traceback (most recent call last):
  File "C:\Users\shaise\Downloads\FreeCAD_0.17\Mod\FreeCAD_SheetMetal\SheetMetalCmd.py", line 713, in execute
    selFaceNames = face, MainObject = Main_Object, sketch = fp.Sketch)
  File "C:\Users\shaise\Downloads\FreeCAD_0.17\Mod\FreeCAD_SheetMetal\SheetMetalCmd.py", line 305, in smBend
    gap2 = gap2, selFaceNames = selFaceNames, automiter = automiter, MainObject = MainObject)
  File "C:\Users\shaise\Downloads\FreeCAD_0.17\Mod\FreeCAD_SheetMetal\SheetMetalCmd.py", line 190, in smMiter
    list2 = MainObject.ancestorsOfType(lenEdge, Part.Face)
<type 'exceptions.ReferenceError'>: This object is immutable, you can not set any attribute or call a non const method

**Comment by jaisekjames** [comment]
Pls see a similar issue &. Comment.
https://forum.freecadweb.org/viewtopic.php?t=29523
Freecad 0.18 having a bug fix by werner two months ago. So I didn't face issue.
commit 7d8e53a

**Comment by shaise** [comment]
This is freecad 0.17.
I can not merge your fixes if break basic stuff. when I download you code, NOTHING works on ver 0.17.
Please install a clean version 17, and try your code.

**Comment by jaisekjames** [comment]
Pls check now. I added copy() to line 668

**Comment by shaise** [comment]
Hi,

It looks like everything works now. Can you please explain, or post a small video in the freecad forum how to use the new features? 
I did not understand how to use sketch wall or sketch guided wall or edge based selection.
The auto mitering looks very good. is it possible to leave some space when doing 90 degrees bends? (when the mitter faces touches it can not be unfolded)

shai

**Comment by ceremcem** [comment]
>  Can you please explain, or post a small video in the freecad forum how to use the new features?

With a cross link here, please.

**Comment by shaise** [comment]
here is the link for his explanation: https://forum.freecadweb.org/viewtopic.php?p=265942&sid=67258351f61f368aa83ea9d2322e0f38#p265944

**Comment by jaisekjames** [comment]
sketch wall was not working. I pushed some update. pls check with updated one.

**Comment by jaisekjames** [comment]
Added gaps to edges for auto-mitering so that it will not touch each other so that unfolding works correctly.

**Comment by shaise** [comment]
looks like there is an error again on ver 0.17. simple bends does not work. Error:
Traceback (most recent call last):
  File "C:\Users\shaise\Downloads\FreeCAD_0.17\Mod\FreeCAD_SheetMetal\SheetMetalCmd.py", line 758, in execute
    selFaceNames = face, MainObject = Main_Object, sketch = fp.Sketch)
  File "C:\Users\shaise\Downloads\FreeCAD_0.17\Mod\FreeCAD_SheetMetal\SheetMetalCmd.py", line 341, in smBend
    gap2 = gap2, selFaceNames = selFaceNames, automiter = automiter, MainObject = MainObject)
  File "C:\Users\shaise\Downloads\FreeCAD_0.17\Mod\FreeCAD_SheetMetal\SheetMetalCmd.py", line 216, in smMiter
    transP = FaceDir * (bendR + thk)
<type 'exceptions.NameError'>: global name 'bendR' is not defined

**Comment by jaisekjames** [comment]
fixed. pls check with updated one.

**Comment by shaise** [comment]
Ok checked and it looks quite stable now.
However, backward compatibility is missing. When I load files from old sheetmetal version and try to change bend properties I get an error, sine new properties are missing. you need to generate default ones when needed. Attached test file. Error:
Traceback (most recent call last):
  File "C:\Users\shaise\Downloads\FreeCAD_0.17\Mod\FreeCAD_SheetMetal\SheetMetalCmd.py", line 757, in execute
    offset = fp.offset.Value, RelifFactor = fp.RelifFactor, UseRelifFactor = fp.UseRelifFactor, automiter = fp.AutoMiter, 
<type 'exceptions.AttributeError'>: 'FeaturePython' object has no attribute 'offset'

[testSheetMetal2.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/2537425/testSheetMetal2.zip)

**Comment by jaisekjames** [comment]
updated. pls check

**Comment by shaise** [comment]
yes! it works now.
It looks pretty stable now so I am merging it into the master repository.
Thank you for your work, these features are great!

**Pull request merged**
