### PR TITLE
OuterWire and Internal Sketches feature

### PR DESCRIPTION
**Pull request by easyw**
- creation of Outer sketch only when possible (outer wire is closed)
- option to select color for internal sketch added

### CODE REVIEW

**Comment by shaise** [comment]
Hi easyw,

Looks good!
Two things we need to consider, though,
1. The unfold script is taken from Ulrich. He should be notified with your changes, or next versions will not be compatible. 
2. Why do you leave the "Unfold_sketch"? It is exactly same as "Unfold_sketch_OutWire" (BTW, I think Outline is better then OutWire)

shai

**Comment by easyw** [comment]
> 1. The unfold script is taken from Ulrich. He should be notified with your changes, or next versions will not be compatible.

@ulrich1a please have a look at this PR (I also notified him at FC forum)
> 2. Why do you leave the "Unfold_sketch"? It is exactly same as "Unfold_sketch_OutWire"

This is not always true... in some case the outline wire is not closed (i.e. when the projection of the unfolded has extra edges on the cut or have internal edges not removed by the unfold script)
outline-sketch
wire-not-closed

> (BTW, I think Outline is better then OutWire)

I've updated it :smile:

**Comment by shaise** [comment]
Thanks easyw.
I have merged the pull request + did some minor layout changes to the gui. 
I will investigate your code some more, perhaps I will use it to replace the current "unfold_sketch"

**Comment by easyw** [comment]
@shaise 
> + did some minor layout changes to the gui.

I manually added the Gui code because the [ui file](https://github.com/shaise/FreeCAD_SheetMetal/blob/master/UnfoldOptions.ui) is outdated...

**Comment by shaise** [comment]
yes I agree. Perhaps I need to remove it.

**Comment by easyw** [comment]
It would be nice to have it updated... it is easier to contribute

**Comment by shaise** [comment]
The problem is I dont know how to insert a custom widget in qdesigner

**Comment by easyw** [comment]
an option is to create a simple button and then change its style
https://stackoverflow.com/questions/15080404/colouring-a-button-in-qt
Just save the ui and then add this code:
```
    mycolor = '#ff5733'
    ui.pushButtonColor.setStyleSheet("background: " + mycolor + ";");
    ui.pushButtonColor.setMaximumWidth(32)
```

[UnfoldOptions.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/2401599/UnfoldOptions.zip)

**Pull request merged**
