### PR TITLE
Translation support improvement

### PR DESCRIPTION
**Pull request by jaisekjames**
* Added Translation support.
* Added shortcut keys
* Improved tool tip

### CODE REVIEW

**Comment by shaise** [comment]
Thank you! very nice job!

**Comment by luzpaz** [comment]
@shaise did you talk with yorik about adding translations for sheetmetal on crowdin ?

**Comment by shaise** [comment]
@luzpaz, no and not familiar with crowdin.

**Comment by luzpaz** [comment]
@shaise https://wiki.freecadweb.org/Translating_an_external_workbench#Send_the_.ts_file_to_a_translation_platform

> It is time to have your .ts file translated. You can choose to set up an account on a public translation platform such as Crowdin or Transifex, or you can benefit from our existing FreeCAD-addons account at Crowdin, which has many users already, and therefore more chance to have your file translated quickly and by people who know FreeCAD.  
> If you wish to host your file on the FreeCAD Crowdin account, get in touch with Yorik on the FreeCAD forum.  
> Note: some platforms like Crowdin can integrate with GitHub and do all the process from points 2, 3 and 4 automatically. For that, you can’t use the FreeCAD Crowdin account; you will need to set up your own account. 

/cc @yorikvanhavre

**Comment by shaise** [comment]
OK understood. I think Freecad account is the best way. I'll try to contact @yorikvanhavre

**Pull request merged**
