### PR TITLE
Some refactoring on bendsolid.

### PR DESCRIPTION
**Pull request by sliptonic**
Some Black() formatting.  Renamed some variables to make the code more readable.
Some minor refactoring.

Added unit test structure and a unit test for get_point_on_cylinder

### CODE REVIEW

**Comment by shaise** [comment]
Hi @sliptonic 

It looks like there are some conflicts.
I recently made quite a lot of bug fixing and algorithm changes to sheetmetal, so this might cause the conflicts.

shai

**Comment by sliptonic** [comment]
Ok.  Rebased and cleaned up.  
This is mostly minor stuff.  variable naming, black(), and a unit test.  
Everything works with my test models but could use a double check.

**Comment by shaise** [comment]
Ok I will take a look. I have added more functionality, this makes bend function work on refined faces as well, and bend solid automatically calculates the thickness. I should add these models as a test case.

**Comment by shaise** [comment]
Ok. It looks like it works on the new test models as well.
I see that you've change the function names and some variables to ["Snake Case" ](https://pythonguides.com/python-naming-conventions/)
Is there a formal naming conversion I should follow?
shai

**Pull request merged**
