### PR TITLE
Rename commands to coincide with Wiki pages

### PR DESCRIPTION
**Pull request by hasecilu**
Same as in Fasteners WB, to be able to use the `What's this?` command we need to synchronize the names.

You need to choose what names you prefer to be used.

| WB name | Wiki name |    |
|---------|-----------|----|
|Base| AddBase|  |
| MakeWall | AddWall |  |
| ExtrudeFace | Extrude |  |
| FoldWall | AddFoldWall |  |
| Unfold | Unfold | OK |
| UnfoldUnattended | UnattendedUnfold |  |
| CornerRelief | AddCornerRelief |  |
| MakeRelief | AddRelief |  | 
| MakeJunction | AddJunction |  |
| MakeBend | AddBend |  |
| SketchOnSheet | SketchOnSheet | OK | 
| FormingWall | Forming | |
| BaseShape | BaseShape | OK |

### CODE REVIEW

**Comment by shaise** [comment]
The problem is, I think, If the command is a creation command, changing it might break old saved files. We need to test it.

**Comment by shaise** [comment]
Ok, I did some checks. The saved files does not hold the command name, they hold the base class of the command. So it probably not hurt old files. It might hurt old macros, but I think this is not a big issue.

**Comment by hasecilu** [comment]
> Ok, I did some checks. The saved files does not hold the command name, they hold the base class of the command. So it probably not hurt old files. It might hurt old macros, but I think this is not a big issue.

Yes, I proposed similar changes on Gears WB and my tests show that the objects only save the class that created them, and as long that doesn't change there is no problems.
https://github.com/looooo/freecad.gears/pull/153

**Comment by hasecilu** [comment]
Now the Wiki pages are being open correctly.

**Comment by shaise** [comment]
Thanks!!

**Pull request merged**
