### PR TITLE
Revert "Fix typo "Substraction" not "Subtraction""

### PR DESCRIPTION
**Pull request by akshimassar**
This reverts commit fef6bb2d310c8f8acc62b242ec8bad54385139e4.
See #240

### CODE REVIEW

**Comment by shaise** [comment]
I just investigated why useSubtraction produced an error for issue #238, and it seems he was trying to load and old file that used the useSubstruction wrong spelling. so perhaps an old version of sheetmetal used the old spelling, and now is incompatible with the new version. I will fix it to support both.

**Comment by luzpaz** [comment]
Any traction on this?

**Comment by shaise** [comment]
I have already fixed it, it now supports both old files and new ones. I did not use this PR since this PR will not be backward compatible

**Comment by luzpaz** [comment]
Thanks. Closing this PR then

**Pull request closed without merging**
