### PR TITLE
Extruded cutout: improve the thickness calculation and other small adjustments

### PR DESCRIPTION
**Pull request by sheetmetalman**

### CODE REVIEW

**Comment by shaise** [comment]
Thanks!

**Comment by shaise** [comment]
@sheetmetalman ,

I have added GUI (Task Panel) to your new feature. Also, as part of a code refactoring I have removed lots of code duplication. 
One of the changes I had to do (for compatibility among other sheetmetal commands) is to rename your SelectedFace property to baseObject.
Please update before adding new changes / fixes.

**Comment by sheetmetalman** [comment]
Awesome!

**Comment by sheetmetalman** [comment]
@shaise Thank you so much! I am testing it now! Very nice!

**Comment by luzpaz** [comment]
Great teamwork here 💪

**Pull request merged**
