### PR TITLE
Bend perforation

### PR DESCRIPTION
**Pull request by Erhannis**
I added the ability to perforate bends, for easy folding.  I tried to make it robust, and it seems to work pretty reliably, though there's a few uncertainties and caveats:
1. In smBend, the `flipped` parameter passed in gets overwritten on each iteration of the sublist.  I don't really understand why or whether there's implications - but it seems to work, so.  (I think it would only matter when the perforation angle is different than the bend angle, fyi.)
2. In the sections labeled "Produce bend Solid" and "Produce unfold Solid" there are blocks
```
if revFace.normalAt(0, 0) != FaceDir:
    revFace.reverse()
```
However, the perforation face I create is composed of multiple faces, so if I try to do the same thing I get error `'Part.Compound' object has no attribute 'normalAt'`.  I don't know why the faces would need to be reversed, so I don't know whether it's a problem here, and it seems to work, so.
3. I'm getting a "Sheet thickness invalid" error when I unfold a shape with nonzero gaps _and_ perforation angle sufficiently greater than bend angle...but hopefully that's really rare in practice, especially because people would usually want perforation the same size as the bend (or less, even), I think.

Overall it seems pretty reliable, though.  I made a D20.
Without perforation:

With perforation:

It bent a lot more easily and accurately with the perforations, naturally.

The size of the perforations is adjustable with perforationMaxLength and nonperforationMaxLength.

Screenshot from 2024-09-14 12-25-10

### CODE REVIEW

**Comment by shaise** [comment]
Hi @Erhannis ,

I Think bend perforations is a great feature, Thnaks!
I need to play with it a bit to see if there are no issues. I will check your concerns as well.
Please just check that it is backward compatible. meaning just load an old version sheetmetal with bends, recompute it and see if there are any issues and that the new parameters are added.

**Comment by Erhannis** [comment]
Oh - as in, save a file with the new Sheet Metal, then roll Sheet Metal back to the master branch, then make sure you can still open the file?  Ok, I'll check.

**Comment by Erhannis** [comment]
It gave me warnings like "icosahedron#Bend018.baseObject auto change element", but no errors; the file loaded and looks fine to me, just missing the perforations themselves.  I then saved the file, checked out feature/perforation again and reloaded, and (with similar warnings) the perforations showed up again.

**Comment by luzpaz** [comment]
@Erhannis would you mind also making sure some of the longer lines in the code be minimized ?

**Comment by shaise** [comment]
> Oh - as in, save a file with the new Sheet Metal, then roll Sheet Metal back to the master branch, then make sure you can still open the file? Ok, I'll check.

No, I meant the opposite. save files in the old sheetmetal and load into new. I don't want to loose the ability to edit old files.

**Comment by Erhannis** [comment]
> @Erhannis would you mind also making sure some of the longer lines in the code be minimized ?

Uh, sure.  I've now folded the longer function calls onto multiple lines in the same style as `smBend`.

> No, I meant the opposite. save files in the old sheetmetal and load into new. I don't want to loose the ability to edit old files.

Ah, right.  I've now tried rolling back to master, created a test file, saved it, checked out feature/perforation, and opened the file successfully.

**Comment by shaise** [comment]
Perhaps I'm doing something wrong, but I cant get the perforation to work.
Attached my file. When I set perforate to True, I get the following error:
```
18:27:00  pyException: Traceback (most recent call last):
  File "C:\Users\Shai\AppData\Roaming\FreeCAD\Mod\FreeCAD_SheetMetal\.\SheetMetalCmd.py", line 1770, in execute
    s, f = smBend(
           ^^^^^^^
  File "C:\Users\Shai\AppData\Roaming\FreeCAD\Mod\FreeCAD_SheetMetal\.\SheetMetalCmd.py", line 1382, in smBend
    perfFace = smMakePerforationFace(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shai\AppData\Roaming\FreeCAD\Mod\FreeCAD_SheetMetal\.\SheetMetalCmd.py", line 195, in smMakePerforationFace
    L0 = (edge.LastParameter - gap2 - lenIPerf2) - (edge.FirstParameter + gap1 + lenIPerf1)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
<class 'ArithmeticError'>: Quantity::operator -(): Unit mismatch in minus operation
18:27:00  Bend: Quantity::operator -(): Unit mismatch in minus operation
```
[testperf1.zip](https://github.com/user-attachments/files/17006335/testperf1.zip)


Another issue: 
All parameters must start with a capital letter.

**Comment by Erhannis** [comment]
Oh, weird - I was using the RealThunder branch, and apparently it does some automatic type conversions or st.  I've added `.Value` on the perforation parameters now to match the other things passed into `smBend`, now it works for me on both the RealThunder branch and the upstream branch.

Re: all parameters must start with a capital letter, which ones do you mean?  Parameters to functions?  All the e.g. `smAddLengthProperty` things?  I tried to mimic the existing code in both places - properties like `gap1` and `radius` and `reliefType` and `minReliefGap` etc. all start with lowercase letters.  I guess there's also `ReliefFactor` and `AutoMiter`, etc.?  So I guess it happens both ways.  And haha, I just noticed I capitalized the property `Perforate`, so I guess I accidentally mimicked that, too.  XD  So...I should make e.g. `perforationAngle` into `PerforationAngle`?

**Comment by shaise** [comment]
> XD So...I should make e.g. perforationAngle into PerforationAngle?

Yes please! I know some others start with lower case, That's for backward compatibility. If I change it to upper case, old files will not load. But for new parameters they should all start with upper case as per freecad standard.

**Comment by Erhannis** [comment]
Ok; I swapped the casing on the properties

**Comment by shaise** [comment]
@Erhannis , Thanks a lot! this is a very nice and handy feature to have!

**Comment by Erhannis** [comment]
@shaise Neat, glad to help!

**Comment by dgrabulosa** [comment]
Nice to have parameter to start-end with a perforation or start-end with solit. In the above photos it star-end with perforation.

**Comment by luzpaz** [comment]
Where will this be documented?

**Comment by Erhannis** [comment]
I can write up some documentation if somebody points me to where it should go

**Comment by shaise** [comment]
this is the place to do it: [https://wiki.freecad.org/SheetMetal_AddWall](url)
But I think you need user permissions. @luzpaz ?

**Pull request merged**
