### PR TITLE
Update SheetMetalFoldCmd.py

### PR DESCRIPTION
**Pull request by praga2018**
This request is for solving the issue in FreeCAD forum : 
https://forum.freecad.org/viewtopic.php?f=3&t=68391&sid=46fb5084ef8914ce8bca89114cc3ee16&start=10
This is the first time, I'm creating pull request. 
Please review and let me know, if any changes are required.

### CODE REVIEW

**Comment by luzpaz** [comment]
Maybe adding code comments explaining what these addition are fixing/avoiding ?

Edit: plural

**Comment by DavidGriffith** [comment]
I think that #229 is the ideal solution since it more directly accesses what's wrong.

**Comment by praga2018** [comment]
> I think that #229 is the ideal solution since it more directly accesses what's wrong.

Agreed with your opinion.

**Comment by luzpaz** [comment]
@praga2018 thanks nevertheless! Feel free to close the ticket.

**Pull request closed without merging**
