### PR TITLE
py3.8 update: time.clock() -> time.process_time()

### PR DESCRIPTION
**Pull request by looooo**
for py2 time.process_time is defined in the FreeCADinit.py:
https://github.com/FreeCAD/FreeCAD/commit/6866397c14226a504232b027b73ce4085e73f01e

### CODE REVIEW

**Comment by shaise** [comment]
is it backward compatible?

**Comment by wwmayer** [comment]
> is it backward compatible?

No. It only works for all FreeCAD versions based on Py3 and FreeCAD v0.19 with Py2. But it doesn't work for FreeCAD v0.18 or older based on Py2. In order to support them too you must add the same workaround as I did in the above commit in looooo's post.

**Comment by shaise** [comment]
@looooo , can you add the workaround at the beginning of the file so it will be backward compatible?

**Comment by looooo** [comment]
@shaise 
You are right. Added the workaround for py2.

**Comment by shaise** [comment]
thanks! merged

**Comment by shaise** [comment]
Tested on v0.17 w/Py2, works. Thanks!

**Pull request merged**
