### PR TITLE
Base feature

### PR DESCRIPTION
**Pull request by jaisekjames**
* Added sketch based Sheet-metal base creation

issues & help needed.
* transaction not happened inside partdesign
* need icon

### CODE REVIEW

**Comment by jaisekjames** [comment]
Added a bug fix for offset not working correctly in last change.

**Comment by jaisekjames** [comment]
* Added icon
* transaction now happened inside partdesign

**Comment by jaisekjames** [comment]
Could you pls check this PR is OK.

**Comment by jaisekjames** [comment]
Could you pls check this PR is OK.

**Comment by shaise** [comment]
sorry about that. was very busy lately. 
do you have any help/tutorial explaining the added features so I can test it?

**Comment by jaisekjames** [comment]
This is starting feature. 

- In case partdesign create a body. 
- then create a sketch closed or open profile. 
- select sketch, base icon will activate. 
- You will have sheet metal profile

**Comment by shaise** [comment]
Hi jaisekjames,

This is a very nice feature!
However you need to properly nest the the feature under the tree. It is different between working inside a body and outside a body. Inside a body each feature is one under the previous one. Outside body, it is like a tree. (please test the original features of the sheetmetal like bend and extend, inside and outside a body, and do the same. Look in the code how I check if it is inside a body or not, and attach the appropriate ViewProvider and do the same)
In the following image I used your feature but the icon became outside the body:
basebend

**Comment by jaisekjames** [comment]
Could you pls check this now. I modified it.

How I add picture here?

**Comment by shaise** [comment]
I just merged your code, Thanks!

To add images here, just drag the image file and drop inside your text.

shai

**Pull request merged**
