### PR TITLE
Forming tool

### PR DESCRIPTION
**Pull request by jaisekjames**
Forming tool.

- First select sheetmetal face
- then continue selection by pressing. select  face to align on forming tool & faces are required to remove
- then press forming icon.
- Adjust sheetmetal thickness if required

Issues

- In Partdesign, link go out of scope. Help?

### CODE REVIEW

**Comment by jaisekjames** [comment]
In Partdesign, We have use shapebinder.

**Comment by shaise** [comment]
I did no understand how to use it. can you attach a freecad file with this feature?

**Comment by jaisekjames** [comment]
pls see link
https://forum.freecadweb.org/viewtopic.php?f=22&t=25281&start=140#p279189

**Comment by shaise** [comment]
Ok I saw your help on freecad forum.
I can not add this feature since the result is not sheet metal, you can not unfold it

**Comment by jaisekjames** [comment]
Ok.

**Comment by jaisekjames** [comment]
Added suppress feature for unfolding.

**Comment by luzpaz** [comment]
Any progress on this?

**Comment by luzpaz** [comment]
@jaisekjames ping

**Comment by shaise** [comment]
This is a new tool created by jaisekjames, however the result is not a compliant sheet metal (can not be unfolded) hence I dont think it should be integrated

**Comment by luzpaz** [comment]
@jaisekjames re-ping

**Comment by luzpaz** [comment]
@jaisekjames bump

**Comment by jaisekjames** [comment]
Forming is destructive type operation. I already added suppress/skip feature, so unfolding will work like normal.

**Comment by jaisekjames** [comment]
Old Branch is not available. so close this & new pull request done.

**Pull request closed without merging**
