### PR TITLE
[WIP] Translation: Adding placeholders

### PR DESCRIPTION
**Pull request by luzpaz**
Not sure how to add translations here yet, so in the meantime putting comments where they need to be. Eventually these commits can be cherry-picked and merged. 

@shaise feel free to help if you can

### CODE REVIEW

**Comment by shaise** [comment]
I tried to read how translate internals work, but could not figure it out. Is it possible to move the translate inside SmWarnDialog, or must it always wrap each text string?

**Comment by luzpaz** [comment]
@yorikvanhavre when you get a chance, care to weigh in?

**Comment by luzpaz** [comment]
@vocx-fc do you mind shedding light on how we can do this ?

**Comment by vocx-fc** [comment]
See this thread for reference, [Updated Localisation Page](https://forum.freecadweb.org/viewtopic.php?p=342336#p342336).

> I'm not entire sure what the differences are, but according to the Qt documentation https://doc.qt.io/qt-5/i18n-source-translation.html, QT_TRANSLATE_NOOP is used outside functions (variable, dictionary definitions, for example), and translate is used within functions (print statements, mostly).

I haven't investigated the differences deeply but for practical matters I would do it like this.

First define the functions
```python
if App.GuiUp:
    from PySide.QtCore import QT_TRANSLATE_NOOP
    from DraftGui import translate
else:
    def QT_TRANSLATE_NOOP(context, text):
        return text

    def translate(context, text):
        return text
```

Use `translate()` inside a print function, and `QT_TRANSLATE_NOOP()` only in dictionary definitions.

Examples,
```python
smWarnDialog("The selected geometry does not belong to the active Body.\n"
             "Please make the container of this item active by\n"
             "double clicking on it.")

smWarnDialog(translate("SheetMetal",
                       "The selected geometry does not belong to the active Body.\n"
                       "Please make the container of this item active by\n"
                       "double clicking on it."))
```

As you will be using the `context=SheetMetal` everywhere, I'd use a shorthand.
```python
def _tr(text):
    return translate("SheetMetal", text)
```
Then
```python
smWarnDialog(_tr("The selected geometry does not belong to the active Body.\n"
                 "Please make the container of this item active by\n"
                 "double clicking on it."))
```
For the properties
```python
obj.addProperty("App::PropertyLength","length","Parameters","Length of wall").length = 10.0

obj.addProperty("App::PropertyLength","length","Parameters",
          QT_TRANSLATE_NOOP("App::Property", "Length of wall")).length = 10.0
```
As I said, I haven't had time to test this exactly, but this is the way it's done in Draft, so by imitating this style, it should work. Once the translate functions are in place, if they don't work for some reason, we can always re-define them, but at least they are there.

See also [Translating_an_external_workbench](https://www.freecadweb.org/wiki/Translating_an_external_workbench).

**Comment by shaise** [comment]
@vocx-fc, is it possible to use _tr inside smWarnDialog() function body
and then everything sent to smWarnDialog() will be translated?

**Comment by vocx-fc** [comment]
Yes, although, I prefer to not do it. Why? Well, a philosophy of Python is that "explicit is better than implicit". If you see the `smWarnDialog(_tr("Something"))` then it is evident that this piece of text is meant to be translated. However, if you don't see the `_tr()` it is not clear if that piece of text is already translated or not.

So, for this case, I prefer to have `_tr()` explicitly there to show other programmers what is actually being translated. Otherwise, another programmer may add a second `translate()` function without realizing there is already one in the back.

**Comment by shaise** [comment]
understand and agree. Further more if I want to show a parameter as well: 
smWarnDialog("Diameter must be more then " + str(diam))
this will totally fail translation.

**Comment by luzpaz** [comment]
Closing in favor of #183  
Great job @jaisekjames

**Pull request closed without merging**
