### PR TITLE
Cca

### PR DESCRIPTION
**Pull request by ceremcem**
* Reverted the definition of K-factor 
* Tidy up the console output 
* Unfold operations uses the K-factor defined in Bend properties. 

Related to #68

### CODE REVIEW

**Comment by shaise** [comment]
why remove the auto k-factor formula?

**Comment by ceremcem** [comment]
@shaise Because this formula is used to determine the K-factor and K-factor is requested from user with an input in the Bend properties. That's why this introduces a UX conflict: Should K-factor be determined by the user, or calculated by SheetMetal WB? It's obvious that the determination of K-factor is tightly related with material properties, so it can't be calculated with such a formula. Besides, this formula needs a citation. The closest formula I can find on the net is the following: 

image

At the best case, this or any other accurate formula should be supplied as a separate tool and actual K-factor should be requested from the user.

**Comment by shaise** [comment]
K-factor can not be taken from the model for 2 reasons:
1. there can be different factors for different bends (usually common when using different bend angles)
2. model can be imported / generated without any folding properties.
Regarding the formula, I agree that maybe it should be some kind of an option, or pop up calculator with selection of common materials.
Regarding ANSI / DIN, perhaps the best option is just to add a global Sheet Metal Workbench preference.

**Comment by ceremcem** [comment]
> Regarding ANSI / DIN, perhaps the best option is just to add a global Sheet Metal Workbench preference.

I agree. This setting should be per project and if it's not explicitly set (then it is a project that uses an older version), user would be clearly informed about the difference and will be required to make the decision. If this preference is set globally, then only the newly created projects will use the global preference.

> there can be different factors for different bends (usually common when using different bend angles)

That is obvious. However, I'm not sure if I could understand this statement as I didn't break anything related to this usage. 

> model can be imported / generated without any folding properties

I didn't understand this one too.

**Comment by ceremcem** [comment]
Oh, I get it now, you mean "K-factor can not be extracted/obtained from the model". 

> there can be different factors for different bends (usually common when using different bend angles)

Currently if user defines the same K-factor for each bend, this value will be used. Otherwise, a proper [error message is displayed](https://github.com/ceremcem/FreeCAD_SheetMetal/blob/ced509a0835aa6a4f3b172ed69963fb0de09ba7e/SheetMetalUnfolder.py#L2181) and operation is aborted. User is still able to follow the "unfold bend by bend" approach though. Currently I don't know how to handle multiple k-factor values but I'm planning to add this support ASAP. Anyway, this is not meant to be a breaking change. 

> model can be imported / generated without any folding properties

Then the user will have to use the "Manual K-factor" input while unfolding.

**Comment by ceremcem** [comment]
@shaise Please let me test more cases as the parameter extraction is not working if the Body is somewhere deep inside several boolean operations.

**Comment by shaise** [comment]
Personally I do not like the fold-by-fold unfold system. It is extremely limited, and can easily brake the model when other features are added. (Which is very common in sheet metal. For example a simple added hole through in the model, disappear after fold-by-fold unfolding:
Before:
bendunfold1
After:
bendunfold2

Using Ulrich's code to unfold will of course work without an issue.
I know that Ulrich was planning to make is code able to handle per-bend K factor, but I don't know the status.
The best way as I see it is to be able to click on bends using the gui, and set the K factor for each bend. This way it will support and sheetmetal object, not only ones generated by the workbench.

**Comment by ceremcem** [comment]
I'm closing this PR regarding to #70

**Pull request closed without merging**
