### PR TITLE
New_extension_method

### PR DESCRIPTION
**Pull request by jaisekjames**
As posted in forum, for testing new extension method

https://forum.freecadweb.org/viewtopic.php?f=22&t=25281&start=170#p294763

### CODE REVIEW

**Comment by shaise** [comment]
my remarks in the forum

**Comment by luzpaz** [comment]
@shaise if you don't mind, in the future, please reference the specific URL directly: https://forum.freecadweb.org/viewtopic.php?f=22&t=25281&start=180#p295682 

Thanks!

**Comment by shaise** [comment]
Will do! sorry for that!

**Comment by jaisekjames** [comment]
closing due new improved version.

**Pull request closed without merging**
